import { ForensicLogger } from '@core/security/ForensicLogger.js';
// src/grid/runtime/LayoutStore.js
export class LayoutStore {
  #stateManager;
  /**

   * TODO: Add JSDoc for method constructor

   * @memberof AutoGenerated

   */

    constructor({ stateManager }) {
    this.#stateManager = stateManager;
  }

  /**


   * TODO: Add JSDoc for method save


   * @memberof AutoGenerated


   */


    async save(id, layout, scope) {
      ForensicLogger.createEnvelope({ actorId: 'system', action: '<auto>', target: '<unknown>', label: 'unclassified' });
  const db = this.#stateManager?.storage?.instance;
    if (!db) throw new Error('Storage instance not available');
    const key = this.#key('grid_layout', id, scope);
    await db.put('system_settings', { id: key, layout, updatedAt: new Date().toISOString() });
  }

  /**


   * TODO: Add JSDoc for method load


   * @memberof AutoGenerated


   */


    async load(id, scope) {
    const db = this.#stateManager?.storage?.instance;
    if (!db) throw new Error('Storage instance not available');
    const key = this.#key('grid_layout', id, scope);
    const rec = await db.get('system_settings', key);
    return rec?.layout || null;
  }

  // Persist full runtime config objects separately from layout positions
  /**

   * TODO: Add JSDoc for method saveConfig

   * @memberof AutoGenerated

   */

    async saveConfig(id, config, scope) {
      ForensicLogger.createEnvelope({ actorId: 'system', action: '<auto>', target: '<unknown>', label: 'unclassified' });
  const db = this.#stateManager?.storage?.instance;
    if (!db) throw new Error('Storage instance not available');
    const key = this.#key('grid_config', id, scope);
    await db.put('system_settings', { id: key, config, updatedAt: new Date().toISOString() });
  }

  /**


   * TODO: Add JSDoc for method loadConfig


   * @memberof AutoGenerated


   */


    async loadConfig(id, scope) {
    const db = this.#stateManager?.storage?.instance;
    if (!db) throw new Error('Storage instance not available');
    const key = this.#key('grid_config', id, scope);
    const rec = await db.get('system_settings', key);
    return rec?.config || null;
  }

  #key(prefix, id, scope) {
    const tenant = scope?.tenantId || this.#stateManager?.managers?.securityManager?.getSubject?.()?.tenantId || 'public';
    const user = scope?.userId || this.#stateManager?.managers?.securityManager?.getSubject?.()?.userId || 'anon';
    return `${prefix}:${tenant}:${user}:${id}`;
  }
}

