/**
 * SafeDOM Utility
 * Provides sanitized DOM manipulation helpers.
 */
export const SafeDOM = {
	/**

	 * TODO: Add JSDoc for method setText

	 * @memberof AutoGenerated

	 */

		setText(el, text) {
		if (!el) return;
		el.textContent = text ?? "";
	},
	/**

	 * TODO: Add JSDoc for method replace

	 * @memberof AutoGenerated

	 */

		replace(el, text) {
		if (!el) return;
		const tmp = document.createElement(el.tagName);
		tmp.textContent = text ?? "";
		el.replaceWith(tmp);
	},
	/**

	 * TODO: Add JSDoc for method insert

	 * @memberof AutoGenerated

	 */

		insert(el, text, pos = "beforeend") {
		if (!el) return;
		el.insertAdjacentText(pos, text ?? "");
	},
};
