/**
 * @file GridHistoryInspector.js
 * @description Minimal overlay to visualize grid history state (undo/redo sizes and last op).
 */

export class GridHistoryInspector {
	#stateManager;
	#el = null;
	#visible = false;

	/**


	 * TODO: Add JSDoc for method constructor


	 * @memberof AutoGenerated


	 */

	constructor({ stateManager }) {
		this.#stateManager = stateManager;
	}

	/**


	 * TODO: Add JSDoc for method initialize


	 * @memberof AutoGenerated


	 */

	initialize() {
		this.#build();
		// Hotkey: Alt+H toggle (avoids F12 conflicts)
		const onKey = (e) => {
			if (e.altKey && e.key?.toLowerCase() === "h") {
				e.preventDefault();
				this.toggle();
			}
		};
		document.addEventListener("keydown", onKey);
		// Auto-update on relevant events
		const update = () => this.#render();
		this.#stateManager?.on?.("operationRecorded", update);
		this.#stateManager?.on?.("layoutRestored", update);
	}

	/**


	 * TODO: Add JSDoc for method toggle


	 * @memberof AutoGenerated


	 */

	toggle() {
		this.#visible = !this.#visible;
		if (!this.#el) this.#build();
		this.#el.style.display = this.#visible ? "block" : "none";
		if (this.#visible) this.#render();
	}

	#build() {
		if (this.#el) return;
		const el = document.createElement("div");
		el.id = "grid-history-inspector";
		el.style.cssText = `
      position: fixed;
      right: 20px;
      bottom: 20px;
      z-index: 10000;
      background: rgba(30,30,30,0.9);
      color: #fff;
      padding: 12px 14px;
      border-radius: 8px;
      font: 12px/1.4 system-ui, -apple-system, Segoe UI, Roboto, sans-serif;
      box-shadow: 0 6px 18px rgba(0,0,0,0.3);
      display: none;
      min-width: 200px;
    `;
		// Build content programmatically to avoid innerHTML
		const headerRow = document.createElement("div");
		headerRow.style.cssText =
			"display:flex; justify-content:space-between; align-items:center; gap:8px; margin-bottom:8px;";
		const title = document.createElement("strong");
		title.textContent = "Grid History";
		const closeBtn = document.createElement("button");
		closeBtn.id = "ghi-close";
		closeBtn.style.cssText =
			"background:#444;color:#fff;border:0;border-radius:4px;padding:4px 6px;cursor:pointer";
		closeBtn.textContent = "×";
		headerRow.appendChild(title);
		headerRow.appendChild(closeBtn);

		const body = document.createElement("div");
		body.id = "ghi-body";

		const controls = document.createElement("div");
		controls.style.cssText = "display:flex; gap:8px; margin-bottom:8px;";
		const undoBtn = document.createElement("button");
		undoBtn.id = "ghi-undo-btn";
		undoBtn.title = "Undo (Ctrl/Cmd+Z)";
		undoBtn.style.cssText =
			"background:#2b7cff;color:#fff;border:0;border-radius:4px;padding:6px 8px;cursor:pointer";
		undoBtn.textContent = "Undo";
		const redoBtn = document.createElement("button");
		redoBtn.id = "ghi-redo-btn";
		redoBtn.title = "Redo (Ctrl/Cmd+Y)";
		redoBtn.style.cssText =
			"background:#2b7cff;color:#fff;border:0;border-radius:4px;padding:6px 8px;cursor:pointer";
		redoBtn.textContent = "Redo";
		controls.appendChild(undoBtn);
		controls.appendChild(redoBtn);

		const undoRow = document.createElement("div");
		undoRow.appendChild(document.createTextNode("Undo: "));
		const undoSpan = document.createElement("span");
		undoSpan.id = "ghi-undo";
		undoSpan.textContent = "0";
		undoRow.appendChild(undoSpan);

		const redoRow = document.createElement("div");
		redoRow.appendChild(document.createTextNode("Redo: "));
		const redoSpan = document.createElement("span");
		redoSpan.id = "ghi-redo";
		redoSpan.textContent = "0";
		redoRow.appendChild(redoSpan);

		const lastRow = document.createElement("div");
		lastRow.appendChild(document.createTextNode("Last: "));
		const lastSpan = document.createElement("span");
		lastSpan.id = "ghi-last";
		lastSpan.textContent = "—";
		lastRow.appendChild(lastSpan);

		const recentLabel = document.createElement("div");
		recentLabel.style.marginTop = "6px";
		recentLabel.textContent = "Recent:";
		const recentList = document.createElement("ul");
		recentList.id = "ghi-recent";
		recentList.style.cssText =
			"margin:6px 0 0 16px; padding:0; list-style:disc; opacity:0.9";

		const toggleInfo = document.createElement("div");
		toggleInfo.style.marginTop = "8px";
		toggleInfo.style.opacity = "0.8";
		toggleInfo.textContent = "Toggle: Alt+H";

		body.appendChild(controls);
		body.appendChild(undoRow);
		body.appendChild(redoRow);
		body.appendChild(lastRow);
		body.appendChild(recentLabel);
		body.appendChild(recentList);
		body.appendChild(toggleInfo);

		el.appendChild(headerRow);
		el.appendChild(body);
		el.querySelector('#ghi-close').addEventListener('click', () => this.toggle()); // prettier-ignore
		el.querySelector('#ghi-undo-btn').addEventListener('click', () => { try { this.#stateManager?.undo?.(); this.#render(); } catch { /* noop */ } }); // prettier-ignore
		el.querySelector('#ghi-redo-btn').addEventListener('click', () => { try { this.#stateManager?.redo?.(); this.#render(); } catch { /* noop */ } }); // prettier-ignore
		document.body.appendChild(el);
		this.#el = el;
	}

	#render() {
		if (!this.#el || !this.#visible) return;
		try {
			const info = this.#stateManager?.getHistoryInfo?.() || {
				undoSize: 0,
				redoSize: 0,
				lastType: null,
				recent: [],
			};
			this.#el.querySelector("#ghi-undo").textContent = String(
				info.undoSize ?? 0
			);
			this.#el.querySelector("#ghi-redo").textContent = String(
				info.redoSize ?? 0
			);
			this.#el.querySelector("#ghi-last").textContent =
				info.lastType || "—";
			const ul = this.#el.querySelector("#ghi-recent");
			ul.replaceChildren();
			(info.recent || []).forEach((t) => {
				const li = document.createElement("li");
				li.textContent = t;
				ul.appendChild(li);
			});
		} catch {
			/* noop */
		}
	}
}

export default GridHistoryInspector;
